name: Dev Branch Build

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
        - run: echo "The job was automatically triggered by a ${{ github.event_name }} event on dev branch."

        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
                      java-version: '17'
                      distribution: 'zulu'
                      cache: gradle

        - name: Cache Gradle dependencies
          uses: actions/cache@v4
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Compile shared module
          run: ./gradlew :shared:compileDebugKotlinAndroid :shared:compileKotlinIosArm64 :shared:compileKotlinIosX64 :shared:compileKotlinIosSimulatorArm64

        - name: Compile Android app
          run: ./gradlew :androidApp:compileDebugKotlin

        - name: Build APK (Debug)
          run: ./gradlew :androidApp:assembleDebug

        - name: Upload APK
          uses: actions/upload-artifact@v4
          with:
            name: debug-apk
            path: androidApp/build/outputs/apk/debug/*.apk