name: Push

on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
                      java-version: '17'
                      distribution: 'zulu'
                      cache: gradle

        - name: Cache Gradle dependencies
          uses: actions/cache@v4
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Run ktlint check
          run: ./gradlew ktlintCheck

        - name: Run detekt
          run: ./gradlew detekt

        - name: Build shared module
          run: ./gradlew :shared:build

        - name: Build Android app
          run: ./gradlew :androidApp:assembleDebug

        - name: Run unit tests
          run: ./gradlew test

        # Uncomment to run UI tests (requires emulator setup)
        # - name: Run Android instrumented tests
        #   uses: reactivecircus/android-emulator-runner@v2
        #   with:
        #     api-level: 29
        #     script: ./gradlew connectedCheck

        - name: Upload test reports
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: test-reports
            path: |
              **/build/reports/
              **/build/test-results/
