name: Production Release (Google Play App Signing)

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  workflow_dispatch:

jobs:
  release:
    name: Release to Google Play
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'zulu'
            cache: gradle

        - name: Cache Gradle dependencies
          uses: actions/cache@v4
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: Read version from properties
          id: version
          run: |
            # Read version from version.properties
            VERSION_CODE=$(grep "VERSION_CODE=" version.properties | cut -d'=' -f2)
            VERSION_NAME=$(grep "VERSION_NAME=" version.properties | cut -d'=' -f2)
            
            echo "Using Version Code: $VERSION_CODE"
            echo "Using Version Name: $VERSION_NAME"
            
            # Set outputs for use in other steps
            echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT
            echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT

        - name: Bump version in build.gradle.kts
          uses: chkfung/android-version-actions@v1.1
          with:
            gradlePath: androidApp/build.gradle.kts
            versionCode: ${{ steps.version.outputs.version_code }}
            versionName: ${{ steps.version.outputs.version_name }}

        - name: Decode upload keystore
          run: |
            echo "${{ secrets.GP_SIGNING_KEY }}" | base64 -d > androidApp/ulchidic.jks

        - name: Build release bundle (signed for upload)
          run: ./gradlew :androidApp:bundleRelease
          env:
            KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
            KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
            KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

        - name: Upload to Google Play Store
          uses: r0adkll/upload-google-play@v1.1.1
          with:
            serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_GP }}
            packageName: ru.dinarastepina.ulchidictionary
            releaseFiles: androidApp/build/outputs/bundle/release/androidApp-release.aab
            track: production
            status: completed

        - name: Upload release bundle
          uses: actions/upload-artifact@v4
          with:
            name: release-bundle
            path: androidApp/build/outputs/bundle/release/*.aab 